name: Deploy to AWS SAM
on:
  push:
    branches: [master]
    paths:
      - "template.yaml"
      - "lambdas/**"
jobs:
  deploy-aws-sam:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: SAM Validate
        run: sam validate

      - name: SAM build
        run: sam build

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name TempFeedbackStack \
            --s3-bucket tempfeedback-bucket \
            --parameter-overrides \
              'APIDomainName=api.tempfeedback.com APICertificateArn=${{ secrets.AWS_CERTIFICATE_ARN }}' \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
